### ISSUE TITLE
issue 1

### ISSUE THREAD

**Issue by mayank408** [mayank408/abc#1]

**Comment by rrishabhj** [comment]
Hey you should definitely read the guidelines first.

**Comment by mayank408** [comment]
@rrishabhj Which guideline are you talking about

**Comment by rrishabhj** [comment]
how to raise a issue. You have to be descriptive of the problem and what are you expecting. Also you should add contribution.md file for more details on the issue, etc. Just google it.

**Comment by anshuman73** [comment]
Basically he means that this issue (and so many others that you have) should explain more than what there is to be done...
